title: Njume
author: Lawrence Njume
description: It's simple. It's easy to use. It's a Jekyll theme.

highlighter: null
permalink: /:title

# https://www.linkedin.com/in/lawrence-njume/
url: https://dietmocha.github.io/blurb/
baseurl:

# Custom options pick here:
# color_scheme: azul|ruby|amber|avocado
color_scheme: royal
