title: Njume
author: Lawrence Njume
description: I am excited about the field of machine learning and look forward to my future with it.

highlighter: null
permalink: /:title

# https://dietmocha.github.io/blurb/
# https://www.linkedin.com/in/lawrence-njume/
url:
baseurl:
# {{site.blurb}} to call this link
blurb: http://dietmocha.github.io/blurb
# Custom options pick here:
# color_scheme: azul|ruby|amber|avocado
color_scheme: royal
