title: Njume
author: Lawrence Njume
description: I am excited about the field of machine learning and look forward to my future with it.

highlighter: null
permalink: /:title

# https://www.linkedin.com/in/lawrence-njume/
url: https://dietmocha.github.io/blurb/
baseurl:

# Custom options pick here:
# color_scheme: azul|ruby|amber|avocado
color_scheme: royal
